# Generated by Django 5.0 on 2024-04-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartChecker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart", models.FileField(upload_to="charts")),
                ("chart_name", models.CharField(blank=True, max_length=200, null=True)),
                ("clean_chart", models.JSONField()),
                ("total_page_count", models.IntegerField(blank=True, null=True)),
                ("character_count", models.IntegerField(blank=True, null=True)),
                ("score", models.CharField(blank=True, max_length=100, null=True)),
                ("chart_response", models.TextField(blank=True, null=True)),
                ("chart_price", models.FloatField(blank=True, null=True)),
                ("is_payment_done", models.BooleanField(default=False)),
                ("is_report_emailed", models.BooleanField(default=False)),
                ("is_state_compliance", models.BooleanField(default=False)),
                (
                    "state_compliance",
                    models.CharField(
                        blank=True,
                        choices=[("Florida", "Florida"), ("California", "California")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_CARF_compliance", models.BooleanField(default=False)),
                ("is_marked_cover_letter", models.BooleanField(default=False)),
                ("is_commission_compliance", models.BooleanField(default=False)),
                ("is_insurance_compliance", models.BooleanField(default=False)),
                (
                    "insurance_compliance",
                    models.CharField(
                        blank=True,
                        choices=[("Aetna", "Aetna"), ("Cigna", "Cigna")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("mr_number", models.CharField(blank=True, max_length=200, null=True)),
                ("is_ss_number", models.BooleanField(default=False)),
                ("ss_number", models.CharField(blank=True, max_length=200, null=True)),
                ("is_driving_license", models.BooleanField(default=False)),
                (
                    "driving_license",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_address", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("is_credit_card", models.BooleanField(default=False)),
                (
                    "credit_card",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
